services:
  testcmaketos7-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/testcmaketos7-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}

  testcmaketos7:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/testcmaketos7:${TAG}
